--CREATE TABLE PROJECT
CREATE TABLE IF NOT EXISTS projects(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL CHECK (name <> ''),
    priority INTEGER NOT NULL,
    description TEXT,
    deliverydate date NOT NULL
);

--CREATE TABLE TASKS
CREATE TABLE IF NOT EXISTS tasks(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL CHECK (name <> ''),
    done BOOLEAN,
    projectId INTEGER REFERENCES projects(id)
);

--INSERT PROJECTS DATA
INSERT INTO projects (name, priority, description, deliverydate) values ('web app',1, 'hecha con js', '2019-05-02');
INSERT INTO projects (name, priority, description, deliverydate) values ('web app 2', 0, 'hecha con react', '2020-05-02');
INSERT INTO projects (name, priority, description, deliverydate) values ('web app 3', 1, 'hecha con angular', '2019-05-02');
INSERT INTO projects (name, priority, description, deliverydate) values ('web app 4', 0, 'hecha con vue', '2020-05-02');
INSERT INTO projects (name, priority, description, deliverydate) values ('web app 5', 1, 'hecha con svelte', '2022-05-02');

--INSERT TASKS DATA
INSERT INTO tasks (name, done, projectId) values ('crear la plantilla base', false, 1);
INSERT INTO tasks (name, done, projectId) values ('descargar react', false, 2);
INSERT INTO tasks (name, done, projectId) values ('descargar angular', true, 3);

